#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: apetrisor
    gecos: Adrian Petrisor
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCit/VDtxUSwcUilSajWQxp7d0d1RRif8WxPjPp/Ij3rPdNU7izqYJpq9RrL+lCMHzM9F6x4qRooe368gnkkjgPz1GiUuV5X41MYBkfIR2VjqeS2SF9fwAONf8rGOCMm7HpTaQSacXbgIaciliS/60uAj2QuIKOt99sz1QzgNQUjSl+SsWlkzLZBvejrHc0tmBMttpp9pe3fwDAYOP3mTBSYPEexrRShpeGsq7ptagtK2jj6rSe6Ii/ypcNcgNmoBd7vtqp1By6xYQJ5nPnT2bmHDBRnuhvFp3v9eODhpU1Nb/EbgcFxTQ2JLudxm3PsB7KuPtf19lGokeBAyPjHLuv7KbLhlm0JkO2mX/1BZaqyHZ4oi7wln/nxsdJJjuArnZjQ7La0AW7YHoe0OcRUFycAjSlWmq8q5FRerVEzsRgplGXUiExuZLUWE8ze8fxgVEeViSvef1FIKLgBSsAQSOSmfWuRXmnYcf2InSnGvfgvtHUim7pdwqoasvYzTrZtJQXbz/KbEa6hNzr/Fn7nZk0YL0Tcd8bjZHX39CGAgBXbjAIqIlIa0j6diK8BkKdK+H+6iU/DghAnjPCB2IqS1QDQFVH0fYNYO4mQnSGprfFSfgVIucG9RldHTBp0fzv6yTlAWAJJtf/3iL88pc+FcOcwNln5Ssf3KE+PIs5edZzHw== adrian.petrisor@fundmore.ai

packages:
#  - golang-go
